import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import clsx from "clsx";
import {getServerSession} from "next-auth";
import {authOptions} from "@/config/auth";
import Link from "next/link";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={clsx('w-screen min-h-screen', inter.className)}>
        <header className={clsx(
          "sticky top-0 h-[48px]",
          "flex justify-end items-center",
          "px-2 md:px-8 py-2",
          "bg-white dark:bg-black shadow-sm",
        )}>
          <Link href="/check-session">
            Session status:
            <span className={clsx("ml-2", session ? 'text-green-500' : 'text-red-500')}>
              {session ? 'Authenticated' : 'Unauthenticated'}
            </span>
          </Link>
        </header>
        {children}
      </body>
    </html>
  )
}
